from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .pose import NODE_CLASS_MAPPINGS as POSE_NODE_CLASS_MAPPINGS
from .pose import NODE_DISPLAY_NAME_MAPPINGS as POSE_NODE_DISPLAY_NAME_MAPPINGS
from .lora_manager import NODE_CLASS_MAPPINGS as LORA_NODE_CLASS_MAPPINGS
from .lora_manager import NODE_DISPLAY_NAME_MAPPINGS as LORA_NODE_DISPLAY_NAME_MAPPINGS
NODE_CLASS_MAPPINGS.update(POSE_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(POSE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(LORA_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(LORA_NODE_DISPLAY_NAME_MAPPINGS)

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
